name: ar_furniture_app
description: AR Destekli Mobilya Dizayn Uygulaması
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.7.0
